model:
  type: gpt2
  hidden_dim: 768
  num_heads: 12
  num_layers: 12
  seq_len: 8192
  scale_attn_by_inverse_layer_idx: true
  gradient_checkpointing: true
  use_flash_attention: true
  flash_attention_block_size: 8192

override_vocab_size: 1127
output_dir: /juice4/scr4/nlp/music/audio-checkpoints/teeu4qs9/step-80000/hf
checkpoint_path: /juice4/scr4/nlp/music/audio-checkpoints/teeu4qs9/step-80000
save_tokenizer: false
